### ISSUE TITLE
WebGL cross browser issues

### ISSUE THREAD

**Issue by ghost** [unc-comp580-comp585/bubble-math#4]
Works on Chrome and Firefox for Federico, but Firefox gives a warning of "Error: WebGL: texImage2D: Conversion requires pixel reformatting."

Does NOT work on Chrome for Ryan with error "Uncaught DOMException: Failed to execute 'texImage2D' on 'WebGLRenderingContext': Tainted canvases may not be loaded.", but does work on Firefox with the same warning.

**Comment by bowerscd** [comment]
per Gary, we only need to conform to chrome standards

**Comment by fmenozzi** [comment]
Even if that's the case, we're still getting inconsistencies on Chrome between mine and Ryan's setup. Not sure if purely OS (Linux vs OS X) or the underlying WebGL/OpenGL implementations.

**Comment by fmenozzi** [comment]
Also, Diane might have less lenient requirements about how portable a web application needs to be.
