### ISSUE TITLE
Rename game modes

### ISSUE THREAD

**Issue by fmenozzi** [unc-comp580-comp585/bubble-math#54]
I don't think "Gamemode 1" and "Gamemode 2" are very descriptive names. I think we should change them. Not sure what to yet, but something like "Basic" for game mode 1 and "Complex" or something for game mode 2. I'm open to suggestions here.

**Comment by ghost** [comment]
Well the modes are basically split into _arithmetic_ (gamemode 1) and _algebra_ (gamemode 2). So I think those are pretty descriptive names.

**Comment by bowerscd** [comment]
Usagi-chan's Bubble Party and Usagi-chan's Bubble Soiree
