### ISSUE TITLE
Controller input for menu navigation

### ISSUE THREAD

**Issue by fmenozzi** [unc-comp580-comp585/bubble-math#62]

**Comment by fmenozzi** [comment]
I think we can also get rid of the "Apply" part; just use the stick to change the option and have it apply immediately, and then press B or something to go back to the main menu

**Comment by bowerscd** [comment]
@fmenozzi the apply part is literally just a back button -> it's a misnomer. Options are already applied as they are changed. You can easily bind that to a button.
