### ISSUE TITLE
Use B instead of select to go back

### ISSUE THREAD

**Issue by fmenozzi** [unc-comp580-comp585/bubble-math#66]
I know the button is technically called Back but it seems like literally every other game ever uses B

**Comment by bowerscd** [comment]
Doesn't make sense for game mode 2. B should be for go back one ring, therefore for consistency we should use Select/Back or Start.

**Comment by fmenozzi** [comment]
Ahh, I didn't realize that we added the ability to go back to the inner ring back in. Any chance we could use start then instead of select? Start generally pauses the game and takes you to a menu, which is what we'd effectively be doing in this case.

**Comment by bowerscd** [comment]
We can bind both. That's fine.
