### ISSUE TITLE
Wonky analog stick navigation in options menu

### ISSUE THREAD

**Issue by fmenozzi** [unc-comp580-comp585/bubble-math#69]
D pad works fine, but the analog stick navigation in the options menu is really bizarre. There's a noticeable delay that prevents me from navigating the menu quickly, and sometimes it takes several tries before a motion up/down/left/right is properly registered, and even then it's sometimes not right (e.g. sometimes it will move up to another option instead of left within an option).

Not sure if this is fixable or just an inherent problem with the analog system but it would be nice if we could fix it (if possible).

**Comment by bowerscd** [comment]
This is your polling system, every 20 polls of the controller. Your choice is delays, or fast af.

**Comment by bowerscd** [comment]
I can switch the left/right motion of the game using the bumpers so that it eliminates the jumping between left/right on options.

**Comment by fmenozzi** [comment]
Then I guess we can try to just decrease it to like 15 or something. All I'm saying is that it currently feels sluggish.
