### ISSUE TITLE
Analog stick allows player to reference bubbles that no longer exist in controller scheme 2

### ISSUE THREAD

**Issue by fmenozzi** [unc-comp580-comp585/bubble-math#72]
D pad works fine in this case, but we should make sure that the bubble at the corresponding angle hasn't been popped (especially since it currently behaves like that bubble is still there e.g. by saying "too small" or "too large")

**Comment by fmenozzi** [comment]
Still getting this problem if the bubble exists in the outer slot but not the inner slot, for example. I think we could try moving the cursor when transitioning from one ring to another if necessary.

**Comment by fmenozzi** [comment]
Still getting this problem. I've attached an example image that shows what's happening. Basically, I selected "3-" in the inner ring (after the outer ring's corresponding bubble at that position had already previously been popped), and it moves to that invalid spot in the outer ring.

![example](https://cloud.githubusercontent.com/assets/4451432/25601067/3603fb74-2eb7-11e7-92a5-9beddeaefff7.png)

**Comment by bowerscd** [comment]
if this is opened again somebody else look at it. My brain is done with this stuff
